server:
  servlet:
    context-path: /api-gateway
  port: 6114
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:6112/registry-service/eureka/
management:
  endpoints:
    web:
      base-path: /api-gateway/actuator
      exposure:
        include: health
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans
logging:
  level:
    org:
      springframework:
        security: "TRACE"
spring:
  application:
    name: api-gateway
  cloud:
    config:
      enabled: false
    gateway:
      routes:
        - id: authentication-server
          uri: lb://authentication-server
          predicates:
            - Path=/authentication-server/**,/oauth2/**,/auth/**,/api-gateway/authentication-server/**,/api-gateway/oauth2/**,/api-gateway/auth/**
          filters:
            - RewritePath=^/api-gateway/(?<p>.*)$, /${p}
            - RewritePath=^/(?<p>oauth2/.*|auth/.*)$, /authentication-server/${p}
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/user-service/**,/user/**,/payments/**,/api-gateway/user-service/**,/api-gateway/user/**,/api-gateway/payments/**
          filters:
            - RewritePath=^/api-gateway/(?<p>.*)$, /${p}
            - RewritePath=^/(?<p>user/.*|payments/.*)$, /user-service/${p}
        - id: saml2-server
          uri: lb://saml2-server
          predicates:
            - Path=/saml2-server/**,/saml/**,/api-gateway/saml2-server/**,/api-gateway/saml/**
          filters:
            - RewritePath=^/api-gateway/(?<p>.*)$, /${p}
            - RewritePath=^/(?<p>saml/.*)$, /saml2-server/${p}