webpackJsonp(["share-module.module"],{

/***/ "../../../../../src/$$_gendir/share-component/share-component.component.css.shim.ngstyle.ts":
/***/ (function(module, __webpack_exports__, __webpack_require__) {

"use strict";
/* harmony export (binding) */ __webpack_require__.d(__webpack_exports__, "a", function() { return styles; });
/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
/* tslint:disable */
/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */ var styles = [''];
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL2hvbWUvZGVwbG95bWVudC9wNW0td2ViL2J1cm4vcHJvZml2ZS13ZWIvc3JjL3NoYXJlLWNvbXBvbmVudC9zaGFyZS1jb21wb25lbnQuY29tcG9uZW50LmNzcy5zaGltLm5nc3R5bGUudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9ob21lL2RlcGxveW1lbnQvcDVtLXdlYi9idXJuL3Byb2ZpdmUtd2ViL3NyYy9zaGFyZS1jb21wb25lbnQvc2hhcmUtY29tcG9uZW50LmNvbXBvbmVudC5jc3MiXSwic291cmNlc0NvbnRlbnQiOlsiICJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7OyJ9
//# sourceMappingURL=share-component.component.css.shim.ngstyle.js.map

/***/ }),

/***/ "../../../../../src/$$_gendir/share-component/share-component.component.ngfactory.ts":
/***/ (function(module, __webpack_exports__, __webpack_require__) {

"use strict";
/* unused harmony export RenderType_ShareComponentComponent */
/* unused harmony export View_ShareComponentComponent_0 */
/* unused harmony export View_ShareComponentComponent_Host_0 */
/* harmony export (binding) */ __webpack_require__.d(__webpack_exports__, "a", function() { return ShareComponentComponentNgFactory; });
/* harmony import */ var __WEBPACK_IMPORTED_MODULE_0__share_component_component_css_shim_ngstyle__ = __webpack_require__("../../../../../src/$$_gendir/share-component/share-component.component.css.shim.ngstyle.ts");
/* harmony import */ var __WEBPACK_IMPORTED_MODULE_1__angular_core__ = __webpack_require__("../../../core/@angular/core.es5.js");
/* harmony import */ var __WEBPACK_IMPORTED_MODULE_2__share_component_share_component_component__ = __webpack_require__("../../../../../src/share-component/share-component.component.ts");
/* harmony import */ var __WEBPACK_IMPORTED_MODULE_3__angular_router__ = __webpack_require__("../../../router/@angular/router.es5.js");
/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
/* tslint:disable */




var styles_ShareComponentComponent = [__WEBPACK_IMPORTED_MODULE_0__share_component_component_css_shim_ngstyle__["a" /* styles */]];
var RenderType_ShareComponentComponent = __WEBPACK_IMPORTED_MODULE_1__angular_core__["ɵcrt"]({ encapsulation: 0,
    styles: styles_ShareComponentComponent, data: {} });
function View_ShareComponentComponent_0(_l) {
    return __WEBPACK_IMPORTED_MODULE_1__angular_core__["ɵvid"](0, [(_l()(), __WEBPACK_IMPORTED_MODULE_1__angular_core__["ɵeld"](0, 0, null, null, 1, 'p', [['style',
                'position:fixed; top:30%; left:50%; transform:translate(-50%,-50%);']], null, null, null, null, null)), (_l()(), __WEBPACK_IMPORTED_MODULE_1__angular_core__["ɵted"](-1, null, ['wait while redirecting\n']))], null, null);
}
function View_ShareComponentComponent_Host_0(_l) {
    return __WEBPACK_IMPORTED_MODULE_1__angular_core__["ɵvid"](0, [(_l()(), __WEBPACK_IMPORTED_MODULE_1__angular_core__["ɵeld"](0, 0, null, null, 1, 'app-share-component', [], null, null, null, View_ShareComponentComponent_0, RenderType_ShareComponentComponent)), __WEBPACK_IMPORTED_MODULE_1__angular_core__["ɵdid"](1, 114688, null, 0, __WEBPACK_IMPORTED_MODULE_2__share_component_share_component_component__["a" /* ShareComponentComponent */], [__WEBPACK_IMPORTED_MODULE_3__angular_router__["a" /* ActivatedRoute */], __WEBPACK_IMPORTED_MODULE_3__angular_router__["o" /* Router */]], null, null)], function (_ck, _v) {
        _ck(_v, 1, 0);
    }, null);
}
var ShareComponentComponentNgFactory = __WEBPACK_IMPORTED_MODULE_1__angular_core__["ɵccf"]('app-share-component', __WEBPACK_IMPORTED_MODULE_2__share_component_share_component_component__["a" /* ShareComponentComponent */], View_ShareComponentComponent_Host_0, {}, {}, []);
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL2hvbWUvZGVwbG95bWVudC9wNW0td2ViL2J1cm4vcHJvZml2ZS13ZWIvc3JjL3NoYXJlLWNvbXBvbmVudC9zaGFyZS1jb21wb25lbnQuY29tcG9uZW50Lm5nZmFjdG9yeS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL2hvbWUvZGVwbG95bWVudC9wNW0td2ViL2J1cm4vcHJvZml2ZS13ZWIvc3JjL3NoYXJlLWNvbXBvbmVudC9zaGFyZS1jb21wb25lbnQuY29tcG9uZW50LnRzIiwibmc6Ly8vaG9tZS9kZXBsb3ltZW50L3A1bS13ZWIvYnVybi9wcm9maXZlLXdlYi9zcmMvc2hhcmUtY29tcG9uZW50L3NoYXJlLWNvbXBvbmVudC5jb21wb25lbnQuaHRtbCIsIm5nOi8vL2hvbWUvZGVwbG95bWVudC9wNW0td2ViL2J1cm4vcHJvZml2ZS13ZWIvc3JjL3NoYXJlLWNvbXBvbmVudC9zaGFyZS1jb21wb25lbnQuY29tcG9uZW50LnRzLlNoYXJlQ29tcG9uZW50Q29tcG9uZW50X0hvc3QuaHRtbCJdLCJzb3VyY2VzQ29udGVudCI6WyIgIiwiPHAgc3R5bGU9XCJwb3NpdGlvbjpmaXhlZDsgdG9wOjMwJTsgbGVmdDo1MCU7IHRyYW5zZm9ybTp0cmFuc2xhdGUoLTUwJSwtNTAlKTtcIj53YWl0IHdoaWxlIHJlZGlyZWN0aW5nXG48L3A+IiwiPGFwcC1zaGFyZS1jb21wb25lbnQ+PC9hcHAtc2hhcmUtY29tcG9uZW50PiJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7Ozs7Ozs7Ozs7b0JDQUE7TUFBQTtNQUFBLDBEQUE4RTtNQUFBOzs7b0JDQTlFO01BQUE7d0NBQUEsVUFBQTtNQUFBO0lBQUE7Ozs7In0=
//# sourceMappingURL=share-component.component.ngfactory.js.map

/***/ }),

/***/ "../../../../../src/$$_gendir/share-component/share-module.module.ngfactory.ts":
/***/ (function(module, __webpack_exports__, __webpack_require__) {

"use strict";
Object.defineProperty(__webpack_exports__, "__esModule", { value: true });
/* harmony export (binding) */ __webpack_require__.d(__webpack_exports__, "ShareModuleModuleNgFactory", function() { return ShareModuleModuleNgFactory; });
/* harmony import */ var __WEBPACK_IMPORTED_MODULE_0__angular_core__ = __webpack_require__("../../../core/@angular/core.es5.js");
/* harmony import */ var __WEBPACK_IMPORTED_MODULE_1__share_component_share_module_module__ = __webpack_require__("../../../../../src/share-component/share-module.module.ts");
/* harmony import */ var __WEBPACK_IMPORTED_MODULE_2__share_component_component_ngfactory__ = __webpack_require__("../../../../../src/$$_gendir/share-component/share-component.component.ngfactory.ts");
/* harmony import */ var __WEBPACK_IMPORTED_MODULE_3__angular_common__ = __webpack_require__("../../../common/@angular/common.es5.js");
/* harmony import */ var __WEBPACK_IMPORTED_MODULE_4__angular_router__ = __webpack_require__("../../../router/@angular/router.es5.js");
/* harmony import */ var __WEBPACK_IMPORTED_MODULE_5__share_component_share_component_component__ = __webpack_require__("../../../../../src/share-component/share-component.component.ts");
/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
/* tslint:disable */






var ShareModuleModuleNgFactory = __WEBPACK_IMPORTED_MODULE_0__angular_core__["ɵcmf"](__WEBPACK_IMPORTED_MODULE_1__share_component_share_module_module__["a" /* ShareModuleModule */], [], function (_l) {
    return __WEBPACK_IMPORTED_MODULE_0__angular_core__["ɵmod"]([__WEBPACK_IMPORTED_MODULE_0__angular_core__["ɵmpd"](512, __WEBPACK_IMPORTED_MODULE_0__angular_core__["ComponentFactoryResolver"], __WEBPACK_IMPORTED_MODULE_0__angular_core__["ɵCodegenComponentFactoryResolver"], [[8, [__WEBPACK_IMPORTED_MODULE_2__share_component_component_ngfactory__["a" /* ShareComponentComponentNgFactory */]]], [3, __WEBPACK_IMPORTED_MODULE_0__angular_core__["ComponentFactoryResolver"]],
            __WEBPACK_IMPORTED_MODULE_0__angular_core__["NgModuleRef"]]), __WEBPACK_IMPORTED_MODULE_0__angular_core__["ɵmpd"](4608, __WEBPACK_IMPORTED_MODULE_3__angular_common__["p" /* NgLocalization */], __WEBPACK_IMPORTED_MODULE_3__angular_common__["o" /* NgLocaleLocalization */], [__WEBPACK_IMPORTED_MODULE_0__angular_core__["LOCALE_ID"]]), __WEBPACK_IMPORTED_MODULE_0__angular_core__["ɵmpd"](512, __WEBPACK_IMPORTED_MODULE_3__angular_common__["b" /* CommonModule */], __WEBPACK_IMPORTED_MODULE_3__angular_common__["b" /* CommonModule */], []),
        __WEBPACK_IMPORTED_MODULE_0__angular_core__["ɵmpd"](512, __WEBPACK_IMPORTED_MODULE_4__angular_router__["r" /* RouterModule */], __WEBPACK_IMPORTED_MODULE_4__angular_router__["r" /* RouterModule */], [[2, __WEBPACK_IMPORTED_MODULE_4__angular_router__["w" /* ɵa */]], [2, __WEBPACK_IMPORTED_MODULE_4__angular_router__["o" /* Router */]]]), __WEBPACK_IMPORTED_MODULE_0__angular_core__["ɵmpd"](512, __WEBPACK_IMPORTED_MODULE_1__share_component_share_module_module__["a" /* ShareModuleModule */], __WEBPACK_IMPORTED_MODULE_1__share_component_share_module_module__["a" /* ShareModuleModule */], []), __WEBPACK_IMPORTED_MODULE_0__angular_core__["ɵmpd"](1024, __WEBPACK_IMPORTED_MODULE_4__angular_router__["m" /* ROUTES */], function () {
            return [[{ path: ':type/:id/:name', component: __WEBPACK_IMPORTED_MODULE_5__share_component_share_component_component__["a" /* ShareComponentComponent */],
                        data: {} }, { path: '', component: __WEBPACK_IMPORTED_MODULE_5__share_component_share_component_component__["a" /* ShareComponentComponent */], data: {} }]];
        }, [])]);
});
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL2hvbWUvZGVwbG95bWVudC9wNW0td2ViL2J1cm4vcHJvZml2ZS13ZWIvc3JjL3NoYXJlLWNvbXBvbmVudC9zaGFyZS1tb2R1bGUubW9kdWxlLm5nZmFjdG9yeS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL2hvbWUvZGVwbG95bWVudC9wNW0td2ViL2J1cm4vcHJvZml2ZS13ZWIvc3JjL3NoYXJlLWNvbXBvbmVudC9zaGFyZS1tb2R1bGUubW9kdWxlLnRzIl0sInNvdXJjZXNDb250ZW50IjpbIiAiXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OzsifQ==
//# sourceMappingURL=share-module.module.ngfactory.js.map

/***/ }),

/***/ "../../../../../src/share-component/share-component.component.ts":
/***/ (function(module, __webpack_exports__, __webpack_require__) {

"use strict";
/* harmony export (binding) */ __webpack_require__.d(__webpack_exports__, "a", function() { return ShareComponentComponent; });
/* harmony import */ var __WEBPACK_IMPORTED_MODULE_0__angular_router__ = __webpack_require__("../../../router/@angular/router.es5.js");
/* harmony import */ var __WEBPACK_IMPORTED_MODULE_1__core_sessions__ = __webpack_require__("../../../../../src/core/sessions.ts");


var ShareComponentComponent = (function () {
    function ShareComponentComponent(_activatedRoute, router) {
        this._activatedRoute = _activatedRoute;
        this.router = router;
    }
    ShareComponentComponent.prototype.ngOnInit = function () {
        var _this = this;
        this._activatedRoute.params.subscribe(function (params) {
            var userAgent = __WEBPACK_IMPORTED_MODULE_1__core_sessions__["a" /* UserSession */].getMobileOperatingSystem();
            var type = params['type'];
            var id = params['id'];
            var name = params['name'];
            if (type && id && name) {
                if (userAgent === 'web') {
                    _this.router.navigate([type, id, name]);
                }
                else if (userAgent === 'Android') {
                    _this.router.navigate([type, id, name]);
                }
                else if (userAgent === 'iOS') {
                    _this.router.navigate([type, id, name]);
                }
                else {
                    _this.router.navigate([type, id, name]);
                }
            }
            else {
                _this.router.navigate(['/']);
            }
        });
    };
    ShareComponentComponent.ctorParameters = function () { return [{ type: __WEBPACK_IMPORTED_MODULE_0__angular_router__["a" /* ActivatedRoute */] }, { type: __WEBPACK_IMPORTED_MODULE_0__angular_router__["o" /* Router */] }]; };
    return ShareComponentComponent;
}());

//# sourceMappingURL=share-component.component.js.map

/***/ }),

/***/ "../../../../../src/share-component/share-module.module.ts":
/***/ (function(module, __webpack_exports__, __webpack_require__) {

"use strict";
/* harmony export (binding) */ __webpack_require__.d(__webpack_exports__, "a", function() { return ShareModuleModule; });
var ShareModuleModule = (function () {
    function ShareModuleModule() {
    }
    return ShareModuleModule;
}());

//# sourceMappingURL=share-module.module.js.map

/***/ })

});
//# sourceMappingURL=share-module.module.chunk.js.map