server:
  port: 5108

spring:
  application:
    name: user-service
  cloud:
    config:
      enabled: false
  datasource:
    url: "jdbc:mysql://${DATABASE_HOST:localhost}:${DATABASE_PORT:3306}/${DATABASE_NAME:login}"
    username: "${DATABASE_USERNAME:root}"
    password: "${DATABASE_PASSWORD:java1234}"
  jpa:
    show-sql: "true"
    hibernate:
      format_sql: "true"
      ddl-auto: "update"

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:5102/eureka/

management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: "http://localhost:9411/api/v2/spans"