server:
  port: '9090'

eureka:
  client:
    serviceUrl:
      defaultZone: http://10.34.0.2:8761/eureka/

management:
  tracing:
    sampling:
      probability: 1.0
      
spring:
  datasource:
    url: "jdbc:mysql://${DATABASE_HOST:localhost}:${DATABASE_PORT:3306}/${DATABASE_NAME:login}"
    username: "${DATABASE_USERNAME:root}"
    password: "${DATABASE_PASSWORD:java1234}"
  jpa:
    show-sql: "true"
  properties:
    hibernate:
      format_sql: "true"
      ddl-auto: "update"

redis:
  port: '6379'
  password: ''
  host: localhost
  
security:
  jwt:
    scope-read: read
    resource-ids: escolaResourceId
    client-secret: escolaClientSecret
    client-id: escolaClientId
    grant-type: password
    scope-write: write
  security-realm: Escola-API
  signing-key: MaYzkSjmkzPC57L
  resource-ids: escolaResourceId
  encoding-strength: '256'

logging:
  level:
    org:
      springframework:
        security: "${SPRING_SECURITY_LOG_LEVEL:TRACE}"
  pattern:
    console: "${LOGPATTERN_CONSOLE:%green(%d{HH:mm:ss.SSS}) %blue(%-5level) %red([%thread]) %yellow(%logger{15}) - %msg%n}"