server:
  port: 7103

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        bootstrap: "false"

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/