server:
  port: 7104

eureka:
  client:
    serviceUrl:
      defaultZone: http://10.34.0.2:8761/eureka/

management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: "http://10.34.0.20:9411/api/v2/spans"

spring:
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/user/**

        - id: saml2-server
          uri: lb://saml2-server
          predicates:
            - Path=/saml/**

        - id: authentication-server
          uri: lb://authentication-server
          predicates:
            - Path=/oauth2/**

        - id: resource-server
          uri: lb://resource-server
          predicates:
            - Path=/login/**