server:
  port: 5104

eureka:
  client:
    serviceUrl:
      defaultZone: "http://10.5.10.2:5102/eureka/"

management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: "http://10.5.10.20:9411/api/v2/spans"

logging:
  level:
    org:
      springframework:
        security: "${SPRING_SECURITY_LOG_LEVEL:TRACE}"
  pattern:
    console: "${LOGPATTERN_CONSOLE:%green(%d{HH:mm:ss.SSS}) %blue(%-5level) %red([%thread]) %yellow(%logger{15}) - %msg%n}"

spring:
  cloud:
    gateway:
      routes:
        - id: authentication-server
          uri: lb://authentication-server
          predicates:
            - Path=/oauth2/**
            - Path=/auth/**
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/user/**
        - id: saml2-server
          uri: lb://saml2-server
          predicates:
            - Path=/saml/**
        - id: resource-server
          uri: lb://resource-server
          predicates:
            - Path=/login/**