server:
  port: 7106
  servlet:
    session:
      timeout: "${SESSION_TIMEOUT:20m}"

spring:
  profiles:
    active: "default"
  application:
    name: resource-server
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: "${JWK_SET_URI:http://10.34.0.5:7105/oauth2/jwks}"
        opaque:
          introspection-uri: "${INTROSPECT_URI:http://10.34.0.5:7105/oauth2/introspect}"
          introspection-client-id: "${INTROSPECT_ID:eazybankintrospect}"
          introspection-client-secret: "${INTROSPECT_SECRET:c1BK9Bg2REeydBbvUoUeKCbD2bvJzXGj}"

eureka:
  client:
    serviceUrl:
      defaultZone: http://10.34.0.2:8761/eureka/

management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: "http://10.34.0.20:9411/api/v2/spans"
logging:
  level:
    org:
      springframework:
        security: "${SPRING_SECURITY_LOG_LEVEL:TRACE}"
  pattern:
    console: "${LOGPATTERN_CONSOLE:%green(%d{HH:mm:ss.SSS}) %blue(%-5level) %red([%thread]) %yellow(%logger{15}) - %msg%n}"