server:
  port: 7107

logging:
  level:
    root: INFO
    org.springframework.web: TRACE
    org.springframework.security: TRACE
    org.springframework.security.saml: TRACE
    org.opensaml.xmlsec: TRACE

eureka:
  client:
    serviceUrl:
      defaultZone: http://10.34.0.2:8761/eureka/

management:
  tracing:
    sampling:
      probability: 1.0

spring:
  security:
    saml2:
      relyingparty:
        registration:
          carsonline:
            signing:
              credentials:
                - private-key-location: "classpath:credentials/private.key"
                  certificate-location: "classpath:credentials/certificate.crt"
            decryption:
              credentials:
                - private-key-location: "classpath:credentials/private.key"
                  certificate-location: "classpath:credentials/certificate.crt"
            assertingparty:
              metadata-uri: "classpath:okta-metadata.xml"