server:
  port: 7108

spring:
  datasource:
    url: "jdbc:mysql://${DATABASE_HOST:10.34.0.11}:${DATABASE_PORT:3306}/${DATABASE_NAME:login}"
    username: "${DATABASE_USERNAME:root}"
    password: "${DATABASE_PASSWORD:java1234}"
  jpa:
    show-sql: "true"
    hibernate:
      format_sql: "true"
      ddl-auto: "update"

eureka:
  client:
    serviceUrl:
      defaultZone: http://10.34.0.2:8761/eureka/

management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: "http://10.34.0.20:9411/api/v2/spans"